classdef Scene
    properties
        Path         = {};       % The path of the scene acquired by OptiMiS, can direct to a single frame, a time series or a z-stack
        Name         = {};       % Name/Names of the images files for a single frame, a time series or a z-stack
        Frame_No     = [];       % Frame number incase of a timeseries or a z-stack
        z_Position   = [];       % in case of a Z - Stack acquizition the z positions of the frame are recorded
        exWavelength = [];       % In case of an excitation spectrum measurements or a dual excitation measurement, the excitation wavelengths are recorded
        TimeStemp    = [];       % In case of a time series all the time stemps of the measured frames are recorded
        Scene_Type   = [];       % Scene type. Options are: Single Image, Excitation Spectrum, Z - Stack, Time Series, Dual Excitation.
        Aqu_Info     = [];       % a structure holding the information from the readme.txt file including all the acquisition parameters...
                                 % such as, Integration time, binning, Number of lines Z position, wavelength, power an more..
        Wavelength;              % wavelength list as generated by the calibration proccess. Read from the Wavelength_Channel calibration.txt file
        wlOrder;                 % This parameter indicates the way the wavelengths are sorted in an accending or descending order.
        currImage_Stack;         % Current Image Stack including the all the images for all the acquired wavelengths.
        currUnmix_Images;        % Unmix result images as calculated using the image stack and the basic spectra.
        Bias = [];               % a number substracted from the image stack which calculated as 95% out of the minimal value of the entire image stack.
        Noise_Dist = [];         % Noise distribution as calculated by substructing the fitted signal, which is the sum of all the individual Tag signals...
                                 %(unmixed values times the there basic spectra) from the raw signal spectrum. This calculation is in pixel level
    end

    methods
        % Add information about the image loaded including aquizition paramters
        Obj = Register_Scene(Obj, Path, Name, nFrame, Spectrum, UnMix_Method, varargin)
        % Load images in .dat format (Old version of the aquizition software)
        Obj = Load_Dat_Images(Obj, Path, First, Last, varargin)
        % Save tiff format files of all the analyzed images including unmixed images, Eapp maps, and donor only image.
        [Eapp, FDonly, FDonly_TH] = Save_Analyzied_Images(Obj, Tags_For_Unmix, Path, Name, Saving_Param)
        Obj = Save_Analyzied_Stacks(Obj, Tags_For_Unmix, Path, Saving_Param)
        Obj = Remove_Scene_fromList(Obj, Scene_Name)
    end

    methods (Static)
        % Load Tiff format image raw data.
        [Image_Stack, Bias]   = Load_Tiff_Image(Name, Path, wlOrder, Hor_Shift, Show_wBar, Remove_HotPixels)
        % Load the aquizition paramters of an image from the readme.txt file
        Aqu_Info              = Load_Aqu_Info (Path, Name)
        % Load wavelength to channel calibration from the relevant text file
        [Wavelength, wlOrder] = Load_Wavelength(Path, Name)
        % Calculate the Sum, average, STD, and mode value of a region of interest within the image
        [Value_Hist, Value, Value_Statistics] = Calc_Hist_Stat(Value, Freq, Mask)
        % Calculate and save histograms of a region of interest in a scene
        [fName, Sheet_Name, Xc, Yc]           = Save_Analyzed_Histograms(Eapp_Hist, FDonly_Hist, Polygon_Cord, Rows_Names_Eapp, Histogram_BinRes, Path, Name, Name_Tag, Statistics, Loop_Index, Polygon_Lable)
        % unmix raw data image stack
        currUnmix_Images      = UnMix(Image_Stack, Spectrum, UnMix_Method, Background)
        % Unmix average region of interestraw data
        [Unmix_Data, Raw_Data_Spect, Area]    = Area_Unmixing_Func(Image_Stack, Tags, Unmix_Method, Area_Unmix, Polygon, Wavelength, Background)
        % Save avarage unmixing of a region of interest.
        Calc_Value            = XLS_Save_Area_Data(Path, Name, Calculate, Tags, Tags_Names, Scene_Inst, Unmix_Method, Area_Unmix, Polygon, Background)
    end
end