%

%------------------------------------------------------------------------

% Copyright (C) 2018  Raicu Lab.
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU Affero General Public License as
%     published by the Free Software Foundation, either version 3 of the
%     License, or (at your option) any later version.
% 
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU Affero General Public License for more details.
% 
%     You should have received a copy of the GNU Affero General Public License
%     along with this program.  If not, see <https://www.gnu.org/licenses/>.
%------------------------------------------------------------------------------
% Writen By: Gabriel Biener, PhD 
% Advisor and Group Leader: Prof. Valerica Raicu
% For technical questions contact biener@uwm.edu
%------------------------------------------------------------------------------
function FRET_2D_Tab_Fcn(FRET_Tool_Kit_FigH, FRET_2D_Tab)

[Calculate_Icon_Image, ~] = imread('.\Icons\Calculator_Button_50x50_3.png');
FRET_2D_Calc_Hist_pButton = uicontrol('Parent', FRET_2D_Tab, 'Tag', 'FRET_2D_Calc_Hist_pButton', ...
                     'Style','pushbutton',...
                     'cdata', Calculate_Icon_Image, 'TooltipString', 'Calculate FRET Data', ...
                     'Position',[20, 10, 50, 50], 'Units','pixels',...
                     'Visible','on',...
                     'FontSize', 10,...
                     'Callback', {@FRET_2D_Calc_Hist_pButton_Callback, FRET_Tool_Kit_FigH});

[Eapp_vs_XA_Icon_Image, ~] = imread('.\Icons\Eapp_vs_XA_50x50.png');
FRET_2D_Plot_EappXA_pButton = uicontrol('Parent', FRET_2D_Tab, 'Tag', 'FRET_2D_Plot_EappXA_pButton', ...
                     'Style','pushbutton',...
                     'cdata', Eapp_vs_XA_Icon_Image, 'TooltipString', 'Plot Eapp vs xA', ...
                     'Position',[90, 10, 50, 50], 'Units','pixels',...
                     'Visible','on',...
                     'FontSize', 10,...
                     'Callback', {@FRET_2D_Plot_EappXA_pButton_Callback, FRET_Tool_Kit_FigH});

[Hist2D_Icon_Image, ~] = imread('.\Icons\Surf_Plot_50x50_4.jpg');
FRET_2D_Calc_2DSpec_pButton = uicontrol('Parent', FRET_2D_Tab, 'Tag', 'FRET_2D_Calc_2DSpec_pButton', ...
                     'Style','pushbutton',...
                     'cdata', Hist2D_Icon_Image, 'TooltipString', '2D FRET Histogram', ...
                     'Position',[160, 10, 50, 50], 'Units','pixels',...
                     'Visible','on',...
                     'FontSize', 10,...
                     'Callback', {@FRET_2D_Calc_2DSpec_pButton_Callback});
end

%------------------------- Callbacks for the Plot Setting Tab widgets --------------------------
% Callback function for the "fluctuation histogram bin" Field. this callback saves values into handles.
