%

%------------------------------------------------------------------------

% Copyright (C) 2018  Raicu Lab.
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU Affero General Public License as
%     published by the Free Software Foundation, either version 3 of the
%     License, or (at your option) any later version.
% 
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU Affero General Public License for more details.
% 
%     You should have received a copy of the GNU Affero General Public License
%     along with this program.  If not, see <https://www.gnu.org/licenses/>.
%------------------------------------------------------------------------------
% Writen By: Gabriel Biener, PhD 
% Advisor and Group Leader: Prof. Valerica Raicu
% For technical questions contact biener@uwm.edu
%------------------------------------------------------------------------------
function FRET_1D_Tab_Fcn(FRET_Tool_Kit_FigH, FRET_1D_Tab)

[Calculate_Icon_Image, ~] = imread('.\Icons\Calculator_Button_50x50_3.png');
FRET_1D_Calc_Hist_pButton = uicontrol('Parent', FRET_1D_Tab, 'Tag', 'FRET_1D_Calc_Hist_pButton', ...
                     'Style','pushbutton',...
                     'cdata', Calculate_Icon_Image, 'TooltipString', 'Calculate FRET Data', ...
                     'Position',[20, 10, 50, 50], 'Units','pixels',...
                     'Visible','on',...
                     'FontSize', 10,...
                     'Callback', {@FRET_1D_Calc_Hist_pButton_Callback, FRET_Tool_Kit_FigH});

[Plot_Hist_Icon_Image, ~] = imread('.\Icons\Histogram_Icon_3.png');
FRET_1D_Plot_Hist_pButton = uicontrol('Parent', FRET_1D_Tab, 'Tag', 'FRET_1D_Plot_Hist_pButton', ...
                     'Style','pushbutton',...
                     'cdata', Plot_Hist_Icon_Image, 'TooltipString', 'Plot ROI Histograms', ...
                     'Position',[90, 10, 50, 50], 'Units','pixels',...
                     'Visible','on',...
                     'FontSize', 10,...
                     'Callback', {@FRET_1D_Plot_Hist_pButton_Callback, FRET_Tool_Kit_FigH});

[Plot_Meta_Icon_Image, ~] = imread('.\Icons\Multi_Curve_Fit.png');
FRET_1D_Calc_Meta_pButton = uicontrol('Parent', FRET_1D_Tab, 'Tag', 'FRET_1D_Calc_Meta_pButton', ...
                     'Style','pushbutton',...
                     'cdata', Plot_Meta_Icon_Image, 'TooltipString', 'Calculate and Plot Meta-Histogram', ...
                     'Position',[160, 10, 50, 50], 'Units','pixels',...
                     'Visible','on',...
                     'FontSize', 10,...
                     'Callback', {@FRET_1D_Calc_Meta_pButton_Callback, FRET_Tool_Kit_FigH});
end